version: '3.9'
services:
    db:
        image: mysql:8.0.29
        command: mysqld --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: always
        environment:
          TZ: "America/Sao_Paulo"
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_USER: docker
          MYSQL_PASSWORD: admin123
          MYSQL_DATABASE: spring_course_one
          MYSQL_ROOT_HOST: "%"
          MYSQL_TCP_PORT: 3308
        ports:
            - "3308:3308"
        expose:
            - "3308"
        networks:
            - "default"
    spring-course-one:
      image: caiquecoelho/spring-course-1
      restart: always
      build: ./
      working_dir: /
      environment:
          TZ: "America/Sao_Paulo"
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/spring_course_one?useTimezone=true&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: docker
          SPRING_DATASOURCE_PASSWORD: admin123
      ports:
        - "8082:80"
      command:
        - mvn spring-boot:run
      depends_on:
        - db
      networks:
        - "default"
networks:
    default:
        driver: bridge