cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:8081
security:
  jwt:
    token:
      secret-key: jwtsecretkey
      expires-length: 3600000
server:
    port: 8082
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_course_one?useTimezone=true&serverTimezone=UTC
      username: root
      password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # hibernate will not change the structure in the database for me, now I'll use flyway
      # ddl-auto: update
    # properties:
     # hibernate:
       # dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 100MB
  application:
    name: spring-course-1
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**
  swagger-ui-path:
    use-root-path: true