name: Continuous Integration with GHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'slim'
        cache: maven

    - name: Show files in the folder
      run: |
          ls
      shell: bash
        
    - name: Build Application JAR
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-course-1:latest ${{ secrets.DOCKER_USERNAME }}/spring-course-1:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-course-1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-course-1:${{ github.run_id }}
